/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jbloom_JBloom */

#ifndef _Included_jbloom_JBloom
#define _Included_jbloom_JBloom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jbloom_JBloom
 * Method:    newbloom
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jbloom_JBloom_newbloom
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    insert
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jbloom_JBloom_insert
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jbloom_JBloom
 * Method:    contains
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_jbloom_JBloom_contains
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jbloom_JBloom
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jbloom_JBloom_clear
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jbloom_JBloom_size
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    elements
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jbloom_JBloom_elements
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    effective_fpp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jbloom_JBloom_effective_1fpp
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    filter_intersect
 * Signature: (Ljbloom/JBloom;Ljbloom/JBloom;)V
 */
JNIEXPORT void JNICALL Java_jbloom_JBloom_filter_1intersect
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    filter_union
 * Signature: (Ljbloom/JBloom;Ljbloom/JBloom;)V
 */
JNIEXPORT void JNICALL Java_jbloom_JBloom_filter_1union
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    filter_difference
 * Signature: (Ljbloom/JBloom;Ljbloom/JBloom;)V
 */
JNIEXPORT void JNICALL Java_jbloom_JBloom_filter_1difference
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jbloom_JBloom_serialize
  (JNIEnv *, jobject);

/*
 * Class:     jbloom_JBloom
 * Method:    native_deserialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_jbloom_JBloom_native_1deserialize
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
